### ISSUE TITLE
Not working in live preview mode

### ISSUE THREAD

**Issue by Gourav1910** [iafisher/obsidian-quick-links#2]
Links are only working in reading mode. Which is making it half useful atleast for me. It should also work in live preview mode so that I can click and go to that link.

**Comment by iafisher** [comment]
Hi, thanks for filing this issue. I should be able to update the plugin to work in live preview mode. I'm not sure if it's possible to make the links work in source editor mode, but I'll keep researching.

**Comment by iafisher** [comment]
@Gourav1910 the plugin now works in live preview mode, once you upgrade to version 0.2.1.
